from fastapi import APIRouter, HTTPException
from fastapi.responses import HTMLResponse
from app.models.handoff import ExpertHandoffRequest, ExpertHandoffResponse
from app.services.expert_handoff_service import ExpertHandoffService
from app.services.passport_engine import PassportEngine

router = APIRouter(prefix="/expert-handoff", tags=["Expert Handoff Bridge"])

@router.post("/dispatch", response_model=ExpertHandoffResponse)
async def dispatch_expert_handoff(req: ExpertHandoffRequest):
    if not req.explicit_dpdp_consent or not req.liability_boundary_acknowledged:
        raise HTTPException(
            status_code=400,
            detail="DPDP Act explicit consent and professional liability boundary acknowledgment are mandatory before routing case."
        )
    return ExpertHandoffService.dispatch_case(req)


@router.get("/dossier/{ticket_id}.pdf", response_class=HTMLResponse)
async def get_handoff_dossier(ticket_id: str):
    """Serve the handoff dossier for a dispatched ticket.

    The dossier is regenerated on demand from the origin passport so the
    download URL advertised in the dispatch response always resolves.
    """
    passport_id = ExpertHandoffService.get_passport_id_for_ticket(ticket_id)
    if not passport_id:
        raise HTTPException(status_code=404, detail="Handoff ticket not found")

    passport = PassportEngine.get_passport(passport_id)
    if not passport:
        raise HTTPException(status_code=404, detail="Passport not found")

    from app.services.rule_engine import DeterministicRuleEngine
    findings = DeterministicRuleEngine.evaluate_passport(
        passport, target_markets=passport.target_markets or ["India"]
    )

    ingest_html = "\n".join(
        f"<tr><td>{ing.raw_name}</td><td>{ing.botanical_name or 'N/A'}</td>"
        f"<td>{ing.api_monograph_id or 'N/A'}</td><td>{ing.plant_part or 'N/A'}</td></tr>"
        for ing in passport.ingredients
    )
    claims_html = "\n".join(f"<li>{c}</li>" for c in passport.proposed_claims)
    finding_rows = "\n".join(
        f"<tr><td>{f.jurisdiction}</td><td>{f.pathway_category}</td><td>{f.explanation_text or f.status}</td></tr>"
        for f in findings
    )

    html_content = f"""<!DOCTYPE html>
<html>
<head><title>IP-SAKTI Expert Handoff Dossier — {ticket_id}</title></head>
<body style="font-family:Arial,sans-serif;margin:40px;color:#333;">
  <div style="text-align:center;border-bottom:3px solid #059669;padding-bottom:16px;">
    <h1 style="color:#065f46;">IP-SAKTI Expert Handoff Dossier</h1>
    <p>Ticket: {ticket_id} | Passport ID: {passport.id}</p>
  </div>
  <h2 style="color:#047857;">Formulation</h2>
  <table style="border-collapse:collapse;" border="1" cellpadding="8">
    <tr><th>Raw Name</th><th>Botanical Name</th><th>API Monograph</th><th>Plant Part</th></tr>
    {ingest_html}
  </table>
  <h2 style="color:#047857;">Proposed Claims</h2>
  <ul>{claims_html}</ul>
  <h2 style="color:#047857;">Regulatory Findings</h2>
  <table style="border-collapse:collapse;" border="1" cellpadding="8">
    <tr><th>Jurisdiction</th><th>Pathway</th><th>Determination</th></tr>
    {finding_rows}
  </table>
  <p style="margin-top:32px;color:#6b7280;">Generated by IP-SAKTI Sahayak. Informational purposes only — not a formal legal opinion.</p>
</body>
</html>"""
    return HTMLResponse(content=html_content)
