"""A4 - Cited compliance dossier generator.

Turns an Innovation Passport into a seven-section, citation-carrying dossier
that a human can hand to a facilitator, bank or IP office. Three rules drive
the design:

1. **No unsourced prose.** Every section is built from passport data, the
   deterministic rule engine, or a retrieved corpus chunk. A section with no
   grounding is labelled ``insufficient`` and listed in ``gaps`` instead of
   being padded with invented text.
2. **Every claim carries a numbered citation** with the exact excerpt and
   source URL, so a reviewer can check each line.
3. **Always a DRAFT.** The dossier states that it is generated, hash-stamped
   and pending human review - it is not a legal opinion.
"""

from __future__ import annotations

import hashlib
import logging
import time
from collections.abc import Callable
from typing import Any

from app.services.passport_engine import PassportEngine
from app.services.rule_engine import DeterministicRuleEngine

logger = logging.getLogger(__name__)

DOSSIER_VERSION = "1.0"
DRAFT_BANNER = "DRAFT - generated by IP-SAKTI, pending human review. Not legal advice."

SECTION_TITLES: list[tuple[str, str]] = [
    ("executive_summary", "1. Executive Summary"),
    ("product_identity", "2. Product and Ingredient Identity"),
    ("prior_art_fto", "3. Prior Art and Freedom to Operate"),
    ("regulatory_pathway", "4. Regulatory Pathway Assessment"),
    ("evidence_support", "5. Evidence and Claim Support"),
    ("risks_gaps", "6. Risks, Gaps and Watch Alerts"),
    ("recommendations", "7. Recommendations and Next Actions"),
]

RISK_ORDER = {"HIGH": 0, "MODERATE": 1, "LOW": 2}

# Per-section retrieval queries - grounded in what the section must prove.
SECTION_QUERIES: dict[str, str] = {
    "prior_art_fto": "patent prior art herbal composition claim similar formulation",
    "regulatory_pathway": "ayurvedic herbal formulation regulatory pathway schedule C CDSCO classical use",
    "risks_gaps": "prohibited ingredient heavy metals adulterant quality standard limit",
}


class DossierError(RuntimeError):
    """Raised when a dossier cannot be produced at all (bad passport id)."""


# ---------------------------------------------------------------------------
# Citations
# ---------------------------------------------------------------------------

def _default_search_fn(query: str, top_k: int = 4) -> list[dict[str, Any]]:
    """Default retrieval: the same hybrid pipeline the chat API uses.

    ``HybridRetriever.retrieve`` is the real entry point (Qdrant + BM25 +
    statutory, then rerank) and returns ``{"sources": [...], ...}``.
    """
    try:
        from app.rag.retrieval_pipeline import HybridRetriever

        result = HybridRetriever.retrieve(query=query, top_k=top_k)
        return list(result.get("sources") or [])
    except Exception as exc:  # noqa: BLE001 - dossier must degrade, not crash
        logger.warning("dossier retrieval failed for %r: %s", query, exc)
        return []


def _cite_fields(source: dict[str, Any]) -> dict[str, Any]:
    return {
        "source": str(source.get("source") or source.get("act_title") or "unknown source"),
        "source_url": str(source.get("source_url") or ""),
        "act_title": str(source.get("act_title") or ""),
        "category": str(source.get("category") or "corpus"),
        "excerpt": str(source.get("content") or source.get("text") or "")[:400],
        "score": float(source.get("score") or source.get("rerank_score") or 0.0),
    }


def collect_citations(
    queries: dict[str, str],
    search_fn: Callable[[str, int], list[dict[str, Any]]] | None = None,
    top_k: int = 4,
) -> list[dict[str, Any]]:
    """Run each section query and return de-duplicated numbered citations."""
    fn = search_fn or _default_search_fn
    citations: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for _section, query in queries.items():
        try:
            sources = fn(query, top_k)
        except Exception as exc:  # noqa: BLE001 - one bad query must not kill the build
            logger.warning("citation query %r failed: %s", query, exc)
            continue
        for source in sources or []:
            fields = _cite_fields(source)
            key = (fields["source"], fields["excerpt"][:60])
            if key in seen or not fields["excerpt"].strip():
                continue
            seen.add(key)
            fields["ref"] = f"[{len(citations) + 1}]"
            citations.append(fields)
    return citations


def citations_for(citations: list[dict[str, Any]], texts: dict[str, str]) -> list[str]:
    """Pick the citations whose excerpt actually overlaps a section's text."""
    out: list[str] = []
    for text in texts.values():
        if not text:
            continue
        probe = " ".join(str(text).lower().split())[:400]
        for cite in citations:
            excerpt = " ".join(str(cite["excerpt"]).lower().split())[:200]
            if excerpt and (excerpt[:80] in probe or probe[:80] in excerpt):
                out.append(str(cite["ref"]))
    unique: list[str] = []
    for ref in out:
        if ref not in unique:
            unique.append(ref)
    return unique


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------

def _section(key: str, body: str, citations: list[dict[str, Any]], **extra: Any) -> dict[str, Any]:
    title = dict(SECTION_TITLES)[key]
    text = str(body or "").strip()
    grounded = bool(citations)
    return {
        "key": key,
        "title": title,
        "body": text,
        "grounding": "cited" if grounded else "insufficient",
        "citations": citations_for(citations, {"body": text}) if text else [],
        **extra,
    }


def _passport_dict(passport: Any) -> dict[str, Any]:
    return {
        "id": passport.id,
        "case_title": passport.case_title,
        "product_form": getattr(passport, "product_form", "") or "",
        "dosage_form": getattr(passport, "dosage_form", "") or "",
        "intended_use": getattr(passport, "intended_use", "") or "",
        "claimed_innovation": getattr(passport, "claimed_innovation", "") or "",
        "process_description": getattr(passport, "process_description", "") or "",
        "target_markets": list(getattr(passport, "target_markets", []) or []),
        "business_role": getattr(passport, "business_role", "") or "",
        "origin_status": getattr(passport, "biological_resource_origin", "") or "",
        "proposed_claims": list(getattr(passport, "proposed_claims", []) or []),
        "ingredients": [
            {
                "raw_name": getattr(i, "raw_name", ""),
                "botanical_name": getattr(i, "botanical_name", "") or "",
                "api_monograph_id": getattr(i, "api_monograph_id", "") or "",
                "plant_part": getattr(i, "plant_part", "") or "",
                "quantity_percentage": getattr(i, "quantity_percentage", 0.0) or 0.0,
                "origin_status": getattr(i, "origin_status", "") or "",
            }
            for i in getattr(passport, "ingredients", []) or []
        ],
        "evidence": [
            {
                "claim_text": getattr(e, "claim_text", ""),
                "evidence_type": getattr(e, "evidence_type", ""),
                "evidence_status": getattr(e, "evidence_status", ""),
                "source_reference": getattr(e, "source_reference", "") or "",
            }
            for e in getattr(passport, "evidence", []) or []
        ],
    }


def _finding_dict(finding: Any) -> dict[str, Any]:
    status = str(getattr(finding, "status", "") or "")
    return {
        "jurisdiction": getattr(finding, "jurisdiction", ""),
        "pathway_category": getattr(finding, "pathway_category", ""),
        "risk_level": getattr(finding, "risk_level", "LOW") or "LOW",
        "status": status,
        "explanation": getattr(finding, "explanation_text", "") or status,
    }


def build_dossier(
    passport_id: str,
    search_fn: Callable[[str, int], list[dict[str, Any]]] | None = None,
    top_k: int = 4,
    watch_alerts: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Build the seven-section dossier for ``passport_id``.

    ``search_fn`` is injectable so the build is fully deterministic offline
    (tests, and the nightly gate) while production uses Unified RAG.
    """
    passport = PassportEngine.get_passport(passport_id)
    if passport is None:
        raise DossierError(f"passport not found: {passport_id}")

    data = _passport_dict(passport)
    markets = data["target_markets"] or ["India"]
    findings = [
        _finding_dict(f)
        for f in DeterministicRuleEngine.evaluate_passport(passport, target_markets=markets)
    ]
    findings.sort(key=lambda f: RISK_ORDER.get(str(f["risk_level"]).upper(), 3))

    citations = collect_citations(SECTION_QUERIES, search_fn=search_fn, top_k=top_k)
    alerts = list(watch_alerts or [])

    ingredient_lines = [
        f"- {i['raw_name']}"
        + (f" ({i['botanical_name']})" if i["botanical_name"] else "")
        + (f" - {i['plant_part']}" if i["plant_part"] else "")
        + (f" - {i['quantity_percentage']}%" if i["quantity_percentage"] else "")
        + (f" - origin: {i['origin_status']}" if i["origin_status"] else "")
        for i in data["ingredients"]
    ]
    claim_lines = [f"{n}. {c}" for n, c in enumerate(data["proposed_claims"], start=1)]
    evidence_lines = [
        f"- [{e['evidence_status']}] {e['claim_text']} ({e['evidence_type']})"
        + (f" - {e['source_reference']}" if e["source_reference"] else "")
        for e in data["evidence"]
    ]
    finding_lines = [
        f"- {f['jurisdiction']} / {f['pathway_category']}: {f['risk_level']} - {f['explanation']}"
        for f in findings
    ]
    alert_lines = [
        f"- [{a.get('match', 'match').upper()}] {a.get('patent_no', '')} {a.get('title', '')}"
        + (f" - overlap: {a.get('overlap', '')}" if a.get("overlap") else "")
        for a in alerts
    ]
    missing_evidence = [e["claim_text"] for e in data["evidence"] if e["evidence_status"] != "VERIFIED"]

    sections = [
        _section(
            "executive_summary",
            (
                f"{data['case_title']} is an Ayurvedic-inspired {data['product_form'] or 'product'}"
                f" ({data['dosage_form'] or 'dosage form not recorded'}) targeting "
                f"{data['intended_use'] or 'use not recorded'}. It contains "
                f"{len(data['ingredients'])} ingredient(s) and {len(data['proposed_claims'])} "
                f"proposed claim(s), assessed for {', '.join(markets)}. "
                f"{len(findings)} regulatory finding(s) were produced by the deterministic "
                f"rule engine; highest risk is {findings[0]['risk_level'] if findings else 'n/a'}."
            ),
            citations,
            stats={
                "ingredients": len(data["ingredients"]),
                "claims": len(data["proposed_claims"]),
                "evidence_items": len(data["evidence"]),
                "findings": len(findings),
                "watch_alerts": len(alerts),
            },
        ),
        _section(
            "product_identity",
            "\n".join(ingredient_lines) or "No ingredients recorded on the passport.",
            citations,
            ingredients=data["ingredients"],
        ),
        _section(
            "prior_art_fto",
            (
                "Prior-art screening is run per formulation through the patent watch service "
                "(A2). New publications matched against the saved profile:\n"
                + "\n".join(alert_lines)
                if alerts
                else "No prior-art alert has been raised for this formulation yet. Run a "
                "patent watch cycle to populate this section; nothing is asserted here "
                "without a retrieved record."
            ),
            citations,
            watch_alerts=alerts,
        ),
        _section(
            "regulatory_pathway",
            "\n".join(finding_lines) or "The rule engine produced no findings for these markets.",
            citations,
            findings=findings,
        ),
        _section(
            "evidence_support",
            ("Proposed claims:\n" + "\n".join(claim_lines) if claim_lines else "No claims recorded.")
            + ("\n\nLinked evidence:\n" + "\n".join(evidence_lines) if evidence_lines else "\n\nNo evidence items are linked to this passport."),
            citations,
            claims=data["proposed_claims"],
            missing_evidence=missing_evidence,
        ),
        _section(
            "risks_gaps",
            "\n".join(alert_lines)
            + ("\n- Missing evidence: " + "; ".join(missing_evidence) if missing_evidence else ""),
            citations,
            gaps=missing_evidence,
        ),
        _section(
            "recommendations",
            _recommendations(findings, missing_evidence, data),
            citations,
        ),
    ]

    gaps = [s["key"] for s in sections if s["grounding"] == "insufficient"]
    dossier: dict[str, Any] = {
        "dossier_version": DOSSIER_VERSION,
        "status": "DRAFT",
        "banner": DRAFT_BANNER,
        "passport_id": data["id"],
        "case_title": data["case_title"],
        "target_markets": markets,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "sections": sections,
        "citations": citations,
        "citation_count": len(citations),
        "ungrounded_sections": gaps,
        "completeness": {
            "sections": len(sections),
            "cited_sections": sum(1 for s in sections if s["grounding"] == "cited"),
            "pct": round(100.0 * sum(1 for s in sections if s["grounding"] == "cited") / len(sections), 1),
        },
    }
    dossier["content_hash"] = content_hash(render_markdown(dossier))
    return dossier


def _recommendations(
    findings: list[dict[str, Any]],
    missing_evidence: list[str],
    data: dict[str, Any],
) -> str:
    lines: list[str] = []
    high = [f for f in findings if str(f["risk_level"]).upper() == "HIGH"]
    if high:
        lines.append(
            "- Resolve HIGH-risk findings first: "
            + "; ".join(f"{f['jurisdiction']} {f['pathway_category']}" for f in high)
        )
    if missing_evidence:
        lines.append("- Attach the missing evidence: " + "; ".join(missing_evidence))
    if not data["origin_status"]:
        lines.append("- Record the biological resource origin status for every ingredient.")
    if not data["target_markets"]:
        lines.append("- Confirm the target markets so the pathway assessment can be scoped.")
    lines.append(
        "- Have a qualified IP facilitator and regulatory specialist sign off before any filing."
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def content_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def render_markdown(dossier: dict[str, Any]) -> str:
    lines = [
        f"# IP-SAKTI Compliance Dossier - {dossier['case_title']}",
        "",
        f"**Status:** {dossier['status']}  ",
        f"**Passport:** `{dossier['passport_id']}`  ",
        f"**Markets:** {', '.join(dossier['target_markets'])}  ",
        f"**Generated:** {dossier['generated_at']}  ",
        f"**Document hash:** `{dossier.get('content_hash') or 'pending'}`  ",
        f"**{dossier['banner']}**",
        "",
    ]
    for section in dossier["sections"]:
        refs = (" " + " ".join(section["citations"])) if section["citations"] else ""
        lines.append(f"## {section['title']}{refs}")
        lines.append("")
        lines.append(section["body"] or "_No content recorded._")
        lines.append("")
    if dossier["citations"]:
        lines.append("## References")
        lines.append("")
        for cite in dossier["citations"]:
            label = cite["act_title"] or cite["source"]
            url = f" - {cite['source_url']}" if cite["source_url"] else ""
            excerpt = cite["excerpt"].replace("\n", " ")[:180]
            lines.append(f"{cite['ref']} {label}{url}")
            lines.append(f"    > {excerpt}")
        lines.append("")
    return "\n".join(lines)


def render_pdf(dossier: dict[str, Any]) -> bytes:
    """Render the dossier to PDF. Raises RuntimeError if reportlab is absent."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.platypus import (
            PageBreak,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
    except ImportError as exc:  # pragma: no cover - dependency is declared
        raise RuntimeError("reportlab is required for PDF export") from exc

    from io import BytesIO

    styles = getSampleStyleSheet()
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        title=f"IP-SAKTI Dossier {dossier['case_title']}",
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
    )
    story: list[Any] = [
        Paragraph(f"IP-SAKTI Compliance Dossier - {dossier['case_title']}", styles["Title"]),
        Paragraph(
            f"Status: {dossier['status']} | Passport: {dossier['passport_id']} | "
            f"Markets: {', '.join(dossier['target_markets'])} | Generated: {dossier['generated_at']}",
            styles["Normal"],
        ),
        Paragraph(f"<b>{dossier['banner']}</b>", styles["Normal"]),
        Paragraph(f"Document hash: {dossier['content_hash']}", styles["Normal"]),
        Spacer(1, 6 * mm),
    ]

    for section in dossier["sections"]:
        refs = (" " + " ".join(section["citations"])) if section["citations"] else ""
        story.append(Paragraph(f"{section['title']}{refs}", styles["Heading2"]))
        for line in (section["body"] or "_No content recorded._").splitlines() or [""]:
            if line.strip():
                story.append(Paragraph(line.replace("&", "&amp;"), styles["BodyText"]))
            else:
                story.append(Spacer(1, 3 * mm))
        if section["key"] == "regulatory_pathway" and section.get("findings"):
            rows = [["Jurisdiction", "Pathway", "Risk", "Explanation"]]
            rows += [
                [f["jurisdiction"], f["pathway_category"], f["risk_level"], f["explanation"]]
                for f in section["findings"]
            ]
            table = Table(rows, colWidths=[28 * mm, 45 * mm, 18 * mm, 78 * mm], repeatRows=1)
            table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#ecfdf5")),
                        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
                        ("FONTSIZE", (0, 0), (-1, -1), 7),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ]
                )
            )
            story.append(table)
            story.append(Spacer(1, 4 * mm))
        if section["key"] == "product_identity" and section.get("ingredients"):
            rows = [["Ingredient", "Botanical name", "Part", "Qty %", "Origin"]]
            rows += [
                [
                    i["raw_name"],
                    i["botanical_name"] or "-",
                    i["plant_part"] or "-",
                    str(i["quantity_percentage"] or "-"),
                    i["origin_status"] or "-",
                ]
                for i in section["ingredients"]
            ]
            table = Table(rows, colWidths=[38 * mm, 45 * mm, 24 * mm, 16 * mm, 30 * mm], repeatRows=1)
            table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#ecfdf5")),
                        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
                        ("FONTSIZE", (0, 0), (-1, -1), 7),
                    ]
                )
            )
            story.append(table)
        story.append(Spacer(1, 4 * mm))

    if dossier["citations"]:
        story.append(PageBreak())
        story.append(Paragraph("References", styles["Heading1"]))
        for cite in dossier["citations"]:
            label = cite["act_title"] or cite["source"]
            url = f" - {cite['source_url']}" if cite["source_url"] else ""
            story.append(Paragraph(f"{cite['ref']} {label}{url}", styles["Normal"]))
            story.append(
                Paragraph(
                    (cite["excerpt"][:220] or "").replace("&", "&amp;"), styles["Italic"]
                )
            )

    def _footer(canvas: Any, _doc: Any) -> None:
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.grey)
        canvas.drawString(18 * mm, 10 * mm, f"IP-SAKTI | {dossier['status']} | hash {dossier['content_hash'][:16]}")
        canvas.restoreState()

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()


def save_dossier_record(
    db: Any,
    passport_id: str,
    user_id: str | None,
    dossier: dict[str, Any],
    doc_format: str = "json",
) -> Any:
    """Persist the dossier so it is auditable and retrievable later."""
    from app.models.db_models import GeneratedDocumentDB

    row = GeneratedDocumentDB(
        passport_id=passport_id,
        user_id=user_id,
        kind="dossier",
        form_code="",
        doc_format=doc_format,
        status="DRAFT",
        content_hash=str(dossier["content_hash"]),
        citation_count=int(dossier["citation_count"]),
        missing_field_count=len(dossier.get("ungrounded_sections") or []),
        summary={
            "case_title": dossier["case_title"],
            "target_markets": dossier["target_markets"],
            "generated_at": dossier["generated_at"],
            "completeness": dossier["completeness"],
            "dossier_version": dossier["dossier_version"],
        },
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    return row
