export const AGENT_BLURBS: Record<string, string> = {
  triz: 'Finds innovative solutions using contradiction analysis and inventive principles.',
  quick_research: 'Scans the tech landscape to extract concepts, trends and evidence fast.',
  find_solutions: 'Diagnoses your problem and recommends the best risk-weighted solution.',
  novelty_search: 'Runs an examiner-style novelty search comparing your idea to prior art.',
  fto_search: 'Checks whether you can make, use and sell your product without infringing patents.',
  design_fto: 'Screens design registrations to confirm your product design is clear to use.',
  patent_drafting: 'Drafts a complete, exam-ready patent application from your invention details.',
  invention_disclosure: 'Captures your raw lab notes into a clean, source-of-truth invention disclosure.',
  office_action_response: 'Triage your patent office objection and drafts a strong reply.',
  essentiality_claim_chart: 'Builds the claim-to-standard mapping chart needed for standard-essential patents.',
  tdoc_novelty_search: 'Assesses your tech disclosure against prior art and flags novelty gaps.',
  document_analyzer: 'Reads and cleans any captured document so it is ready for downstream analysis.',
  lca_biotherapeutic: 'Prioritises biotherapeutic drug candidates with an evidence-based lead analysis.',
  lca_small_molecule: 'Prioritises small-molecule candidates through a chemical-identity first screen.',
  sar_data_extraction: 'Extracts structure-activity relationship data with strict validation.',
  antibody_target_predictor: 'Predicts antibody targets using an evidence hierarchy and sequence QC.',
  markush_drafting: 'Drafts precise Markush claims with verified chemical structures.',
  formulation: 'Builds regulatory-first formulation ideas for your product category.',
  materials_find_solutions: 'Solves material problems with evidence-based root-cause analysis.',
};